
package instameet.client;

import java.util.List;
import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.ws.Action;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.9-b130926.1035
 * Generated source version: 2.2
 * 
 */
@WebService(name = "InstaMeetService", targetNamespace = "http://service/")
@XmlSeeAlso({
    ObjectFactory.class
})
public interface InstaMeetService {


    /**
     * 
     * @param arg2
     * @param arg1
     * @param arg0
     * @return
     *     returns boolean
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "visitAppointment", targetNamespace = "http://service/", className = "instameet.client.VisitAppointment")
    @ResponseWrapper(localName = "visitAppointmentResponse", targetNamespace = "http://service/", className = "instameet.client.VisitAppointmentResponse")
    @Action(input = "http://service/InstaMeetService/visitAppointmentRequest", output = "http://service/InstaMeetService/visitAppointmentResponse")
    public boolean visitAppointment(
        @WebParam(name = "arg0", targetNamespace = "")
        String arg0,
        @WebParam(name = "arg1", targetNamespace = "")
        int arg1,
        @WebParam(name = "arg2", targetNamespace = "")
        int arg2);

    /**
     * 
     * @param arg1
     * @param arg0
     * @return
     *     returns instameet.client.User
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "getOwnData", targetNamespace = "http://service/", className = "instameet.client.GetOwnData")
    @ResponseWrapper(localName = "getOwnDataResponse", targetNamespace = "http://service/", className = "instameet.client.GetOwnDataResponse")
    @Action(input = "http://service/InstaMeetService/getOwnDataRequest", output = "http://service/InstaMeetService/getOwnDataResponse")
    public User getOwnData(
        @WebParam(name = "arg0", targetNamespace = "")
        String arg0,
        @WebParam(name = "arg1", targetNamespace = "")
        int arg1);

    /**
     * 
     * @param arg2
     * @param arg1
     * @param arg0
     * @return
     *     returns boolean
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "addFriend", targetNamespace = "http://service/", className = "instameet.client.AddFriend")
    @ResponseWrapper(localName = "addFriendResponse", targetNamespace = "http://service/", className = "instameet.client.AddFriendResponse")
    @Action(input = "http://service/InstaMeetService/addFriendRequest", output = "http://service/InstaMeetService/addFriendResponse")
    public boolean addFriend(
        @WebParam(name = "arg0", targetNamespace = "")
        String arg0,
        @WebParam(name = "arg1", targetNamespace = "")
        int arg1,
        @WebParam(name = "arg2", targetNamespace = "")
        int arg2);

    /**
     * 
     * @param arg1
     * @param arg0
     * @return
     *     returns java.util.List<instameet.client.Appointment>
     */
    @WebMethod(operationName = "GetAppointments")
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "GetAppointments", targetNamespace = "http://service/", className = "instameet.client.GetAppointments")
    @ResponseWrapper(localName = "GetAppointmentsResponse", targetNamespace = "http://service/", className = "instameet.client.GetAppointmentsResponse")
    @Action(input = "http://service/InstaMeetService/GetAppointmentsRequest", output = "http://service/InstaMeetService/GetAppointmentsResponse")
    public List<Appointment> getAppointments(
        @WebParam(name = "arg0", targetNamespace = "")
        String arg0,
        @WebParam(name = "arg1", targetNamespace = "")
        int arg1);

    /**
     * 
     * @param arg1
     * @param arg0
     * @return
     *     returns instameet.client.User
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "createUser", targetNamespace = "http://service/", className = "instameet.client.CreateUser")
    @ResponseWrapper(localName = "createUserResponse", targetNamespace = "http://service/", className = "instameet.client.CreateUserResponse")
    @Action(input = "http://service/InstaMeetService/createUserRequest", output = "http://service/InstaMeetService/createUserResponse")
    public User createUser(
        @WebParam(name = "arg0", targetNamespace = "")
        String arg0,
        @WebParam(name = "arg1", targetNamespace = "")
        String arg1);

    /**
     * 
     * @param arg1
     * @param arg0
     * @return
     *     returns java.util.List<java.lang.String>
     */
    @WebMethod(operationName = "GetMessages")
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "GetMessages", targetNamespace = "http://service/", className = "instameet.client.GetMessages")
    @ResponseWrapper(localName = "GetMessagesResponse", targetNamespace = "http://service/", className = "instameet.client.GetMessagesResponse")
    @Action(input = "http://service/InstaMeetService/GetMessagesRequest", output = "http://service/InstaMeetService/GetMessagesResponse")
    public List<String> getMessages(
        @WebParam(name = "arg0", targetNamespace = "")
        String arg0,
        @WebParam(name = "arg1", targetNamespace = "")
        int arg1);

    /**
     * 
     * @param arg2
     * @param arg1
     * @param arg0
     * @return
     *     returns boolean
     */
    @WebMethod(operationName = "SendMessage")
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "SendMessage", targetNamespace = "http://service/", className = "instameet.client.SendMessage")
    @ResponseWrapper(localName = "SendMessageResponse", targetNamespace = "http://service/", className = "instameet.client.SendMessageResponse")
    @Action(input = "http://service/InstaMeetService/SendMessageRequest", output = "http://service/InstaMeetService/SendMessageResponse")
    public boolean sendMessage(
        @WebParam(name = "arg0", targetNamespace = "")
        String arg0,
        @WebParam(name = "arg1", targetNamespace = "")
        int arg1,
        @WebParam(name = "arg2", targetNamespace = "")
        String arg2);

    /**
     * 
     * @param arg2
     * @param arg1
     * @param arg0
     * @return
     *     returns boolean
     */
    @WebMethod(operationName = "UpdateLocation")
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "UpdateLocation", targetNamespace = "http://service/", className = "instameet.client.UpdateLocation")
    @ResponseWrapper(localName = "UpdateLocationResponse", targetNamespace = "http://service/", className = "instameet.client.UpdateLocationResponse")
    @Action(input = "http://service/InstaMeetService/UpdateLocationRequest", output = "http://service/InstaMeetService/UpdateLocationResponse")
    public boolean updateLocation(
        @WebParam(name = "arg0", targetNamespace = "")
        String arg0,
        @WebParam(name = "arg1", targetNamespace = "")
        int arg1,
        @WebParam(name = "arg2", targetNamespace = "")
        Location arg2);

    /**
     * 
     * @param arg1
     * @param arg0
     * @return
     *     returns java.util.List<instameet.client.User>
     */
    @WebMethod(operationName = "GetFriends")
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "GetFriends", targetNamespace = "http://service/", className = "instameet.client.GetFriends")
    @ResponseWrapper(localName = "GetFriendsResponse", targetNamespace = "http://service/", className = "instameet.client.GetFriendsResponse")
    @Action(input = "http://service/InstaMeetService/GetFriendsRequest", output = "http://service/InstaMeetService/GetFriendsResponse")
    public List<User> getFriends(
        @WebParam(name = "arg0", targetNamespace = "")
        String arg0,
        @WebParam(name = "arg1", targetNamespace = "")
        int arg1);

    /**
     * 
     * @param arg1
     * @param arg0
     * @return
     *     returns boolean
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "verifyUser", targetNamespace = "http://service/", className = "instameet.client.VerifyUser")
    @ResponseWrapper(localName = "verifyUserResponse", targetNamespace = "http://service/", className = "instameet.client.VerifyUserResponse")
    @Action(input = "http://service/InstaMeetService/verifyUserRequest", output = "http://service/InstaMeetService/verifyUserResponse")
    public boolean verifyUser(
        @WebParam(name = "arg0", targetNamespace = "")
        String arg0,
        @WebParam(name = "arg1", targetNamespace = "")
        int arg1);

    /**
     * 
     * @param arg2
     * @param arg1
     * @param arg0
     * @return
     *     returns instameet.client.Appointment
     */
    @WebMethod(operationName = "CreateAppointments")
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "CreateAppointments", targetNamespace = "http://service/", className = "instameet.client.CreateAppointments")
    @ResponseWrapper(localName = "CreateAppointmentsResponse", targetNamespace = "http://service/", className = "instameet.client.CreateAppointmentsResponse")
    @Action(input = "http://service/InstaMeetService/CreateAppointmentsRequest", output = "http://service/InstaMeetService/CreateAppointmentsResponse")
    public Appointment createAppointments(
        @WebParam(name = "arg0", targetNamespace = "")
        String arg0,
        @WebParam(name = "arg1", targetNamespace = "")
        int arg1,
        @WebParam(name = "arg2", targetNamespace = "")
        Appointment arg2);

    /**
     * 
     * @param arg1
     * @param arg0
     * @return
     *     returns java.util.List<instameet.client.Location>
     */
    @WebMethod(operationName = "GetFriendLocations")
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "GetFriendLocations", targetNamespace = "http://service/", className = "instameet.client.GetFriendLocations")
    @ResponseWrapper(localName = "GetFriendLocationsResponse", targetNamespace = "http://service/", className = "instameet.client.GetFriendLocationsResponse")
    @Action(input = "http://service/InstaMeetService/GetFriendLocationsRequest", output = "http://service/InstaMeetService/GetFriendLocationsResponse")
    public List<Location> getFriendLocations(
        @WebParam(name = "arg0", targetNamespace = "")
        String arg0,
        @WebParam(name = "arg1", targetNamespace = "")
        int arg1);

    /**
     * 
     * @param arg2
     * @param arg1
     * @param arg0
     * @return
     *     returns instameet.client.Location
     */
    @WebMethod(operationName = "GetFriendLocation")
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "GetFriendLocation", targetNamespace = "http://service/", className = "instameet.client.GetFriendLocation")
    @ResponseWrapper(localName = "GetFriendLocationResponse", targetNamespace = "http://service/", className = "instameet.client.GetFriendLocationResponse")
    @Action(input = "http://service/InstaMeetService/GetFriendLocationRequest", output = "http://service/InstaMeetService/GetFriendLocationResponse")
    public Location getFriendLocation(
        @WebParam(name = "arg0", targetNamespace = "")
        String arg0,
        @WebParam(name = "arg1", targetNamespace = "")
        int arg1,
        @WebParam(name = "arg2", targetNamespace = "")
        int arg2);

    /**
     * 
     * @param arg1
     * @param arg0
     * @return
     *     returns instameet.client.LoginData
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "login", targetNamespace = "http://service/", className = "instameet.client.Login")
    @ResponseWrapper(localName = "loginResponse", targetNamespace = "http://service/", className = "instameet.client.LoginResponse")
    @Action(input = "http://service/InstaMeetService/loginRequest", output = "http://service/InstaMeetService/loginResponse")
    public LoginData login(
        @WebParam(name = "arg0", targetNamespace = "")
        String arg0,
        @WebParam(name = "arg1", targetNamespace = "")
        String arg1);

}
